export const ContentData = [
  { key: '1 ', name: ' Tate Muli Zhuba Lyedu' },
  { key: '2 ', name: ' Ngatu mbonkeniye Jesu' },
  { key: '3 ', name: ' Hosana Wokudenga' },
  { key: '4 ', name: ' Unkujeni Mose Banhu' },
  { key: '5 ', name: ' Nsungunuli Wedu' },
  { key: '6 ', name: ' Tine Chipo Chikulwana' },
  { key: '7 ', name: ' Ndingolinga Unchinjikwa' },
  { key: '8 ', name: ' Mwakakamhililwa  Imi' },
  { key: '9 ', name: ' Ndamilika Imi Ndimunda Kudenga' },
  { key: '10', name: ' Jesu Imwi Munzila' },
  { key: '11', name: ' Lingisani  Mujibone' },
  { key: '12', name: ' Ndilingeni Neshe Jenu' },
  { key: '13', name: ' Isu Banhu Mune Nyika' },
  { key: '14', name: ' Shomejani Mahwi Enu' },
  { key: '15', name: ' Zhajisani Chilebo Chenu' },
  { key: '16', name: ' Ngana Ndavumisisa' },
  { key: '17', name: ' Yobu Buulemu' },
  { key: '18', name: ' Dade Ndili Mwana Wenu' },
  { key: '19', name: ' Mwali Tate Mulosiswa' },
  { key: '20', name: ' Ishe Hobu Bupenyu Bwangu' },
  { key: '21', name: ' Yomo Munzi Mwa Davida' },
  { key: '22', name: ' Kristu Nsungunuli Wedu' },
  { key: '23', name: ' Ishe Kana Ndilashika' },
  { key: '24', name: ' Ncheji Wangu NdiJehova' },
  { key: '25', name: ' Mune Mwizi Jenu IShe' },
  { key: '26', name: ' Muna Banhu Benu Mwali' },
  { key: '27', name: ' Nditungamile Jehova' },
  { key: '28', name: ' Pezhulu Kuna Mwali' },
  { key: '29', name: ' Yokudenga Kuna Tate' },
  { key: '30', name: ' Bane Mazha Ibo Zwabo' },
  { key: '31', name: ' Jerusalema Unsha Wangu' },
  { key: '32', name: ' Ndipeni  Bomesho Ndilinge' },
  { key: '33', name: ' Timo munzila yenyika yobupenyu' },
  { key: '34', name: ' Isabatha nasi Jesu' },
  { key: '35', name: ' Izhuba lyesondo lyaswika nasi' },
  { key: '36', name: ' Ishe Tabungana' },
  { key: '37', name: ' Wakatola cinkwa Jesu' },
  { key: '38', name: ' Yolo lubimbo  lusimu' },
  { key: '39', name: ' Tilibalyijani, Tilibalyijani' },
  { key: '40', name: ' Mashango ose nda peja' },
  { key: '41', name: ' Ndipeni bo yezwo zwipo' },
  { key: '42', name: ' Ishe wangu kana ndilingisa' },
  { key: '43', name: ' Lubimbo lwangu lupopa' },
  { key: '44', name: ' Bokani zwenu Jehova' },
  { key: '45', name: ' Hoyu Unshingili Wangu' },
  { key: '46', name: ' Ndino Shamiswa Zwangu' },
  { key: '47', name: ' Ndahwa Ihwi Lyenu' },
  { key: '48', name: ' Ishe Ndihweni Nokushanta' },
  { key: '49', name: ' Lyakanaka Yelyo Zhuba' },
  { key: '50', name: ' Mwali Ndiye Swingo Yangu' },
]